update fish_functions

diff --git a/private_dot_config/private_fish/dot_fish_functions b/private_dot_config/private_fish/dot_fish_functions
--- a/private_dot_config/private_fish/dot_fish_functions
+++ b/private_dot_config/private_fish/dot_fish_functions
@@ -16,33 +16,34 @@
 # end
 
 function bind_bang
-  switch (commandline -t)
-  case "!"
-    commandline -t $history[1]; commandline -f repaint
-  case "*"
-    commandline -i !
-  end
+    switch (commandline -t)
+        case "!"
+            commandline -t $history[1]
+            commandline -f repaint
+        case "*"
+            commandline -i !
+    end
 end
 
 function bind_dollar
-  switch (commandline -t)
-  case "!"
-    commandline -t ""
-    commandline -f history-token-search-backward
-  case "*"
-    commandline -i '$'
-  end
+    switch (commandline -t)
+        case "!"
+            commandline -t ""
+            commandline -f history-token-search-backward
+        case "*"
+            commandline -i '$'
+    end
 end
 
 function fish_user_key_bindings
-  bind ! bind_bang
-  bind '$' bind_dollar
-  fzf_key_bindings
+    bind ! bind_bang
+    bind '$' bind_dollar
+    fzf_key_bindings
 end
 
 # Git log find by commit message
 function glf
-  git log --all --grep=$argv
+    git log --all --grep=$argv
 end
 
 # function vim
@@ -51,82 +52,82 @@ end
 
 # Git find all commits unique to a current branch
 function gitu
-  git log (git rev-parse --abbrev-ref HEAD) --not (git for-each-ref --format='%(refname)' refs/heads/ | grep -v "refs/heads/"(git rev-parse --abbrev-ref HEAD))
+    git log (git rev-parse --abbrev-ref HEAD) --not (git for-each-ref --format='%(refname)' refs/heads/ | grep -v "refs/heads/"(git rev-parse --abbrev-ref HEAD))
 end
 
 # Diff current branch with specified branch
 function gdh
-  git diff $argv HEAD
+    git diff $argv HEAD
 end
 
 # Diff current branch with specified branch using difftool
 function gdlh
-  git difftool $argv HEAD | less
+    git difftool $argv HEAD | less
 end
 
 function gro
-  gron $argv[2] | fgrep $argv[1] | norg
+    gron $argv[2] | fgrep $argv[1] | norg
 end
 
 function findbyport
-  # sudo lsof -i :$argv
-  lsof -i :$argv | grep \* | cut -d ' ' -f5
+    # sudo lsof -i :$argv
+    lsof -i :$argv | grep \* | cut -d ' ' -f5
 end
 
 function killbyport
-  kill -9 (findbyport $argv)
+    kill -9 (findbyport $argv)
 end
 
 # https://github.com/SidOfc/dotfiles/tree/master/.config/fish/functions
 # https://medium.com/@sidneyliebrand/how-fzf-and-ripgrep-improved-my-workflow-61c7ca212861
 function kp --description "Kill processes"
-  set -l __kp__pid (ps -ef | sed 1d | eval "fzf $FZF_DEFAULT_OPTS -m --header='[kill:process]'" | awk '{print $2}')
-  set -l __kp__kc $argv[1]
+    set -l __kp__pid (ps -ef | sed 1d | eval "fzf $FZF_DEFAULT_OPTS -m --header='[kill:process]'" | awk '{print $2}')
+    set -l __kp__kc $argv[1]
 
-  if test "x$__kp__pid" != "x"
-    if test "x$argv[1]" != "x"
-      echo $__kp__pid | xargs kill $argv[1]
-    else
-      echo $__kp__pid | xargs kill -9
+    if test "x$__kp__pid" != x
+        if test "x$argv[1]" != x
+            echo $__kp__pid | xargs kill $argv[1]
+        else
+            echo $__kp__pid | xargs kill -9
+        end
+        kp
     end
-    kp
-  end
 end
 
 function fp --description "Search your path"
-  set -l loc (echo $PATH | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:path]'")
+    set -l loc (echo $PATH | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:path]'")
 
-  if test (count $loc) = 1
-    set -l cmd (rg --files -L $loc | rev | cut -d'/' -f1 | rev | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:exe] => $loc'")
-    if test (count $cmd) = 1
-      echo $cmd
-    else
-      fp
+    if test (count $loc) = 1
+        set -l cmd (rg --files -L $loc | rev | cut -d'/' -f1 | rev | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:exe] => $loc'")
+        if test (count $cmd) = 1
+            echo $cmd
+        else
+            fp
+        end
     end
-  end
 end
 
 function bip --description "Install brew plugins"
-  set -l inst (brew search | eval "fzf $FZF_DEFAULT_OPTS -m --header='[brew:install]'")
+    set -l inst (brew search | eval "fzf $FZF_DEFAULT_OPTS -m --header='[brew:install]'")
 
-  if not test (count $inst) = 0
-    for prog in $inst
-      brew install "$prog"
+    if not test (count $inst) = 0
+        for prog in $inst
+            brew install "$prog"
+        end
     end
-  end
 end
 
 function pbclear --description "Provide functionality to clear from the pasteboard (the Clipboard) from command line"
-  if test (which pbcopy)
-    echo '' | pbcopy
-  end
+    if test (which pbcopy)
+        echo '' | pbcopy
+    end
 end
 
 function reload --description "Reload fish shell"
-  if contains -- -f $argv
-    set -e __initialized
-  end
-  source ~/.config/fish/config.fish
+    if contains -- -f $argv
+        set -e __initialized
+    end
+    source ~/.config/fish/config.fish
 end
 
 # search for a pattern in files, then fuzzy select file and open in nvim
@@ -138,50 +139,50 @@ function rgvim
 end
 
 function install -d "Interactive package installer"
-  if [ $argv[1] ]
-    set choice $argv[1]
-  else
-    set choice (brew search | fzf --reverse --preview "brew info {}" --preview-window=right:75%)
-  end
-  if [ $choice ]
-    brew install $choice
-  end
+    if [ $argv[1] ]
+        set choice $argv[1]
+    else
+        set choice (brew search | fzf --reverse --preview "brew info {}" --preview-window=right:75%)
+    end
+    if [ $choice ]
+        brew install $choice
+    end
 end
 
 # https://github.com/junegunn/fzf/wiki/Examples-(fish)
 function fzf-bcd-widget -d 'cd backwards'
-	pwd | awk -v RS=/ '/\n/ {exit} {p=p $0 "/"; print p}' | tail -r | eval (__fzfcmd) +m --select-1 --exit-0 $FZF_BCD_OPTS | read -l result
-	[ "$result" ]; and cd $result
-	commandline -f repaint
+    pwd | awk -v RS=/ '/\n/ {exit} {p=p $0 "/"; print p}' | tail -r | eval (__fzfcmd) +m --select-1 --exit-0 $FZF_BCD_OPTS | read -l result
+    [ "$result" ]; and cd $result
+    commandline -f repaint
 end
 
 # TODO bind to shortcut
 function fzf-cdhist-widget -d 'cd to one of the previously visited locations'
-	# Clear non-existent folders from cdhist.
-	set -l buf
-	for i in (seq 1 (count $dirprev))
-		set -l dir $dirprev[$i]
-		if test -d $dir
-			set buf $buf $dir
-		end
-	end
-	set dirprev $buf
-	string join \n $dirprev | tail -r | sed 1d | eval (__fzfcmd) +m --tiebreak=index --toggle-sort=ctrl-r $FZF_CDHIST_OPTS | read -l result
-	[ "$result" ]; and cd $result
-	commandline -f repaint
+    # Clear non-existent folders from cdhist.
+    set -l buf
+    for i in (seq 1 (count $dirprev))
+        set -l dir $dirprev[$i]
+        if test -d $dir
+            set buf $buf $dir
+        end
+    end
+    set dirprev $buf
+    string join \n $dirprev | tail -r | sed 1d | eval (__fzfcmd) +m --tiebreak=index --toggle-sort=ctrl-r $FZF_CDHIST_OPTS | read -l result
+    [ "$result" ]; and cd $result
+    commandline -f repaint
 end
 
 function fco -d "Fuzzy-find and checkout a branch"
-  git branch --all | grep -v HEAD | string trim | fzf | read -l result; and git checkout "$result"
+    git branch --all | grep -v HEAD | string trim | fzf | read -l result; and git checkout "$result"
 end
 
 function fcoc -d "Fuzzy-find and checkout a commit"
-  git log --pretty=oneline --abbrev-commit --reverse | fzf --tac +s -e | awk '{print $1;}' | read -l result; and git checkout "$result"
+    git log --pretty=oneline --abbrev-commit --reverse | fzf --tac +s -e | awk '{print $1;}' | read -l result; and git checkout "$result"
 end
 
 # count file occurences of a specified pattern
 function rgc
-  echo File occurences: (rgn $argv[1] | wc -l | string trim)
+    echo File occurences: (rgn $argv[1] | wc -l | string trim)
 end
 
 # use diff-so-fancy for a single/multiple changed files
@@ -191,16 +192,19 @@ end
 
 # compare current branch with a specified remote branch
 function gdrb
-  git fetch; git diff ...origin/$argv
+    git fetch
+    git diff ...origin/$argv
 end
 
 # compare logs of a current branch with a specified remote branch
 function glrb
-  git fetch; git log ...origin/$argv
+    git fetch
+    git log ...origin/$argv
 end
 
 function mkcd
-  mkdir -pv $argv; cd $argv
+    mkdir -pv $argv
+    cd $argv
 end
 
 # function nvm_find_nvmrc
@@ -225,41 +229,61 @@ end
 # end
 
 function commit-count
-  git rev-list --count HEAD
+    git rev-list --count HEAD
 end
 
 function count_commits
-  commit-count
+    commit-count
 end
 
 function diff_commits
-  if test $argv[1]
-    git log --left-right --graph --cherry-pick --oneline (git rev-parse --abbrev-ref HEAD)...$argv[1]
-  else
-    echo "Branch name is required"
-  end
+    if test $argv[1]
+        git log --left-right --graph --cherry-pick --oneline (git rev-parse --abbrev-ref HEAD)...$argv[1]
+    else
+        echo "Branch name is required"
+    end
 end
 
 function build_status
-  if test $argv[1]
-    set projectname $argv[1]
-  else
-    set projectname "lwa-ui-dev-build"
-  end
+    if test $argv[1]
+        set projectname $argv[1]
+    else
+        set projectname lwa-ui-dev-build
+    end
 
-  echo $projectname
+    echo $projectname
 
-  set id $(aws codebuild list-builds-for-project --project-name $projectname | jq -r '.ids[0]')
-  aws codebuild batch-get-builds --ids "$id" | jq '.builds[].phases[] | select (.phaseType=="BUILD") | .phaseStatus'
+    set id $(aws codebuild list-builds-for-project --project-name $projectname | jq -r '.ids[0]')
+    aws codebuild batch-get-builds --ids "$id" | jq '.builds[].phases[] | select (.phaseType=="BUILD") | .phaseStatus'
 end
 
 function yy
-	set tmp (mktemp -t "yazi-cwd.XXXXXX")
-	yazi $argv --cwd-file="$tmp"
-	if set cwd (command cat -- "$tmp"); and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
-		builtin cd -- "$cwd"
-	end
-	rm -f -- "$tmp"
+    set tmp (mktemp -t "yazi-cwd.XXXXXX")
+    yazi $argv --cwd-file="$tmp"
+    if set cwd (command cat -- "$tmp"); and [ -n "$cwd" ]; and [ "$cwd" != "$PWD" ]
+        builtin cd -- "$cwd"
+    end
+    rm -f -- "$tmp"
+end
+
+function cmus
+    # Check if cmuscontrold is available
+    if type -q cmuscontrold
+        # Start cmuscontrold in a subshell that waits for cmus to finish
+        begin
+            cmuscontrold >/tmp/cmuscontrold-log.txt 2>&1 &
+            set -l cmuscontrold_pid $last_pid
+
+            # Run cmus and wait for it to exit
+            command cmus
+
+            # Kill cmuscontrold when cmus exits
+            kill $cmuscontrold_pid
+        end
+    else
+        # Run cmus normally if cmuscontrold is unavailable
+        command cmus
+    end
 end
 
 # vim: filetype=fish
