Fix bootstrap recovery and fish helper edge cases

diff --git a/private_dot_config/private_fish/dot_fish_functions b/private_dot_config/private_fish/dot_fish_functions
--- a/private_dot_config/private_fish/dot_fish_functions
+++ b/private_dot_config/private_fish/dot_fish_functions
@@ -80,16 +80,11 @@ function kp --description "Kill processes"
 end
 
 function fp --description "Search your path"
-    set -l loc (echo $PATH | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:path]'")
-
-    if test (count $loc) = 1
-        set -l cmd (rg --files -L $loc | rev | cut -d'/' -f1 | rev | tr ' ' '\n' | eval "fzf $FZF_DEFAULT_OPTS --header='[find:exe] => $loc'")
-        if test (count $cmd) = 1
-            echo $cmd
-        else
-            fp
-        end
-    end
+    set -l loc (printf '%s\n' $PATH | fzf --no-multi --header='[find:path]'); or return
+    test (count $loc) -eq 1; or return 1
+    set -l cmd (rg --files -L -- "$loc" | string replace -r '^.*/' '' | fzf --no-multi --header="[find:exe] => $loc"); or return
+    test (count $cmd) -eq 1; or return 1
+    printf '%s\n' "$cmd"
 end
 
 function bip --description "Install brew packages (fzf picker if no args)"
@@ -228,16 +223,27 @@ function diff_commits
 end
 
 function build_status
-    if test $argv[1]
-        set projectname $argv[1]
-    else
-        set projectname lwa-ui-dev-build
+    if test (count $argv) -gt 1; or contains -- '' $argv
+        echo "usage: build_status [PROJECT]" >&2
+        return 2
     end
+    set -l projectname lwa-ui-dev-build
+    test (count $argv) -eq 0; or set projectname "$argv[1]"
 
     echo $projectname
 
-    set id $(aws codebuild list-builds-for-project --project-name $projectname | jq -r '.ids[0]')
+    set -l builds (aws codebuild list-builds-for-project --project-name "$projectname"); or return
+    set -l id (printf '%s\n' $builds | jq -er '.ids[0] | select(type == "string" and length > 0)')
+    set -l lookup_status $status
+    if test $lookup_status -ne 0
+        echo "build_status: could not find a build ID for $projectname" >&2
+        return $lookup_status
+    end
     aws codebuild batch-get-builds --ids "$id" | jq '.builds[].phases[] | select (.phaseType=="BUILD") | .phaseStatus'
+    set -l build_statuses $pipestatus
+    for step_status in $build_statuses
+        test $step_status -eq 0; or return $step_status
+    end
 end
 
 function yy
